print('HELLO, WELCOME TO MY QUICK PERSONAL SURVEY!')
print('What is your name?')
name = input('Enter name: ')
print('Welcome to my survey, ' + name + '!')
print('Let\'s get started! What is your favorite movie?')
movie = input('Enter your movie: ')
print(movie + ' is a good one!')
print('What is your favorite all time dish?')
dish = input('Enter a dish: ')
print('You can never go wrong with ' + dish + '!')
print('What was the name of your first love?')
love = input('Enter name: ')
print(love + ' ehh? okay.')
print('If you could have one exotic pet, what would you have?')
pet = input('Enter pet: ')
print('Whoaaa! ' 'A ' + pet + ' is a cool looking animal.')
print('I\'m running out of questions... Come back later for more? xD')